feat(src/models/Pets.js) defini modelo pets
aaronstz/PF-Rebirth pull request #4
Opened 2022-07-20 23:16 UTC by lucasdiaz7

duda si incorporar las propiedades de estado y urgente

2022-07-20 23:19 UTC, TobiasTymkiw reviewed
Nose que podemos hacer con el estado y urgente

2022-07-20 23:21 UTC, TobiasTymkiw approved these changes

2022-07-21 13:26 UTC, marugramajo requested changes
flasheaste

2022-07-21 19:38 UTC, marugramajo approved these changes

2022-07-21 19:45 UTC, Enzosanchezz approved these changes

2022-07-21 20:04 UTC, merged